//aws_access_key = ""
//aws_secret_key = ""
myami = "ami-026ebd4cfe2c043b2"
mykey = "*****"
tags = ["postgresql", "nodejs", "react"]
instancetype = "t2.micro"
controlinstancetype = "t3a.micro"
num = 3
region = "us-east-1"
mysecgr = "ansible-project-sec-gr"
user = "*****"
